/**
 * 잡사바 로컬 상품 카탈로그.
 *
 * - Supabase 키가 없을 때 스토어 화면(홈·카테고리·검색·베스트·신상품·1+1·상품 상세)이 이 데이터를 읽는다.
 * - supabase/migrations/20261008100400_seed.sql 의 상품·옵션·이미지·리뷰는 이 파일과 같은 내용이다.
 *   상품을 고치면 seed SQL도 같이 맞춰 주세요. (id 규칙: 상품 5ab00000-…-{no}, 옵션 5ab10000-…-{no}{index})
 * - 상품명·문구는 잡사바 오리지널이며, 사업자·제조원·연락처는 모두 "예시" 값이다.
 */

export type StorageType = "room" | "refrigerated" | "frozen";

export type PackShape = "oil-bottle" | "fish-bottle" | "sauce-bottle" | "onggi" | "glass-jar" | "tray" | "pouch" | "gift-box";

export type Motif =
  | "sesame"
  | "perilla"
  | "chili"
  | "garlic"
  | "soybean"
  | "anchovy"
  | "sandlance"
  | "tuna"
  | "roe"
  | "shrimp"
  | "squid"
  | "oyster"
  | "barley"
  | "leaf"
  | "onion"
  | "radish"
  | "burdock"
  | "egg"
  | "garlicscape"
  | "hairtail"
  | "pollock"
  | "drop";

export type CatalogCategory = {
  id: string;
  slug: string;
  name: string;
  description: string;
  tagline: string;
};

export type CatalogVariant = {
  id: string;
  sku: string;
  optionName: string;
  listPrice: number;
  salePrice: number;
  stock: number;
};

export type CatalogReview = {
  id: string;
  name: string;
  rating: number;
  content: string;
  date: string;
  option?: string;
};

export type CatalogProduct = {
  no: number;
  id: string;
  slug: string;
  name: string;
  summary: string;
  categorySlug: string;
  tag: string;
  storage: StorageType;
  isBest: boolean;
  isNew: boolean;
  isOnePlusOne: boolean;
  salesCount: number;
  createdAt: string;
  variants: CatalogVariant[];
  foodType: string;
  ingredients: string;
  origin: string;
  allergens: string;
  shelfLife: string;
  storageMethod: string;
  story: string;
  points: { title: string; body: string }[];
  pairings: string[];
  howTo: string;
  reviews: CatalogReview[];
  images: { src: string; alt: string }[];
  art: {
    shape: PackShape;
    motif: Motif;
    /** 내용물 색 */
    fill: string;
    /** 뚜껑/캡 색 */
    cap: string;
    /** 라벨 보조 문구 */
    labelSub: string;
  };
};

export const SELLER_INFO = {
  manufacturer: "잡사바 식품 (예시) · 전라북도 순창군 장류로 00 (예시)",
  seller: "잡사바 (예시)",
  phone: "1588-0000 (예시)",
} as const;

export const CATALOG_CATEGORIES: CatalogCategory[] = [
  { id: "a1000000-0000-4000-8000-000000000001", slug: "sauce", name: "소스", description: "참기름·들기름부터 비빔장, 조림간장까지. 한 숟갈이면 맛이 잡히는 양념.", tagline: "참기름 · 들기름 · 양념장" },
  { id: "a1000000-0000-4000-8000-000000000002", slug: "jang", name: "장류", description: "고추장, 된장, 간장, 청국장. 찬장의 기본을 항아리에서 천천히.", tagline: "고추장 · 된장 · 간장" },
  { id: "a1000000-0000-4000-8000-000000000003", slug: "jangajji", name: "장아찌", description: "간장에 절여 아삭함을 남긴 밥상 단골. 꺼내서 바로 올리세요.", tagline: "마늘 · 깻잎 · 고추" },
  { id: "a1000000-0000-4000-8000-000000000004", slug: "banchan", name: "반찬", description: "매일 꺼내 먹는 작은 찬. 덜 달고 덜 짜게 조렸습니다.", tagline: "멸치볶음 · 장조림 · 콩자반" },
  { id: "a1000000-0000-4000-8000-000000000005", slug: "jeotgal", name: "젓갈", description: "명란·창난 같은 밥도둑 젓갈과 국·김치 맛을 잡는 액젓.", tagline: "명란 · 창난 · 액젓" },
  { id: "a1000000-0000-4000-8000-000000000006", slug: "gift", name: "세트·선물", description: "고마운 분께, 우리 집 찬장에. 잡사바 대표 상품을 한 상자에.", tagline: "장독 · 기름 · 젓갈 세트" },
];

const pid = (no: number) => `5ab00000-0000-4000-8000-${String(no).padStart(12, "0")}`;
const vid = (no: number, index: number) => `5ab10000-0000-4000-8000-${String(no).padStart(6, "0")}${String(index).padStart(6, "0")}`;
const rid = (no: number, index: number) => `5ab20000-0000-4000-8000-${String(no).padStart(6, "0")}${String(index).padStart(6, "0")}`;

type VariantInput = [sku: string, optionName: string, listPrice: number, salePrice: number, stock: number];
type ReviewInput = [name: string, rating: number, content: string, date: string, option?: string];

type ProductInput = Omit<CatalogProduct, "id" | "variants" | "reviews" | "images"> & {
  variants: VariantInput[];
  reviews: ReviewInput[];
  extraImages?: { src: string; alt: string }[];
  mainImage?: { src: string; alt: string };
};

function product(input: ProductInput): CatalogProduct {
  const { variants, reviews, extraImages, mainImage, ...rest } = input;
  const packshot = { src: `/images/products/${input.slug}.webp`, alt: `잡사바 ${input.name} 패키지` };
  const detail = { src: `/images/products/${input.slug}-detail.webp`, alt: `${input.name} 담음새` };
  const images = mainImage ? [mainImage, packshot, ...(extraImages ?? []), detail] : [packshot, ...(extraImages ?? []), detail];
  return {
    ...rest,
    id: pid(input.no),
    variants: variants.map(([sku, optionName, listPrice, salePrice, stock], index) => ({
      id: vid(input.no, index + 1),
      sku,
      optionName,
      listPrice,
      salePrice,
      stock,
    })),
    reviews: reviews.map(([name, rating, content, date, option], index) => ({
      id: rid(input.no, index + 1),
      name,
      rating,
      content,
      date,
      option,
    })),
    images,
  };
}

const ROOM_OIL = "직사광선을 피해 서늘한 곳에 두세요. 개봉 후에는 뚜껑을 꼭 닫아 3개월 안에 드세요.";
const COLD = "0~10℃ 냉장 보관. 개봉 후에는 덜어 드시고 깨끗한 수저를 사용해 주세요.";
const COLD_JEOT = "0~5℃ 냉장 보관, 오래 두실 때는 -18℃ 이하 냉동 보관. 해동 후 재냉동하지 마세요.";

export const CATALOG_PRODUCTS: CatalogProduct[] = [
  // ───────────── 소스 ─────────────
  product({
    no: 1,
    slug: "jobsaba-chamgireum",
    name: "잡사바 통참깨 참기름",
    summary: "국산 통참깨를 낮은 온도로 한 번만 짜낸, 첫 숟갈부터 고소한 참기름.",
    categorySlug: "sauce",
    tag: "참기름·들기름",
    storage: "room",
    isBest: true,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 1840,
    createdAt: "2026-06-02T09:00:00+09:00",
    variants: [
      ["JS-SAU-SES-180", "180ml", 16900, 14900, 120],
      ["JS-SAU-SES-300", "300ml", 26900, 22900, 86],
      ["JS-SAU-SES-300X2", "300ml × 2병", 53800, 43900, 40],
    ],
    foodType: "참기름",
    ingredients: "참깨 100% (국산)",
    origin: "참깨: 국산",
    allergens: "참깨 함유. 이 제품은 들깨를 사용한 제품과 같은 시설에서 착유합니다.",
    shelfLife: "제조일로부터 18개월 (병 하단 표기일까지)",
    storageMethod: ROOM_OIL,
    story:
      "참깨는 볶는 정도에서 맛이 갈립니다. 잡사바 참기름은 국산 통참깨를 작은 솥에서 나눠 볶아 탄 향 없이 고소한 향만 남겼고, 압착은 한 번으로 끝냈습니다. 그래서 색은 맑은 호박빛이고 끝맛이 깔끔합니다. 나물 한 접시, 비빔밥 한 그릇에 한 바퀴만 둘러도 '이 집 참기름 좋다'는 말이 나옵니다. 한번 잡숨봐, 바로 압니다.",
    points: [
      { title: "국산 통참깨 100%", body: "섞지 않은 국산 참깨만 씁니다. 원산지는 로트마다 확인합니다." },
      { title: "저온 볶음 · 1회 압착", body: "소량씩 볶아 쓴맛과 탄내를 줄이고 첫 기름만 담았습니다." },
      { title: "맑은 호박빛", body: "앙금을 충분히 가라앉혀 색이 맑고 향이 오래 갑니다." },
    ],
    pairings: ["시금치·고사리 나물", "비빔밥과 간장계란밥", "소금 참기름장에 삼겹살", "미역국 마무리 한 방울"],
    howTo: "익힌 요리는 불을 끈 뒤 마지막에, 나물은 간을 본 다음 한 바퀴 둘러 주세요. 센 불 조리보다는 향을 살리는 마무리용으로 권합니다.",
    reviews: [
      ["김*연", 5, "병뚜껑 열자마자 고소한 냄새가 확 올라와요. 나물 무칠 때 양을 반으로 줄여도 충분합니다.", "2026-09-21", "300ml"],
      ["박*호", 5, "색이 맑아서 처음엔 연한가 했는데 향이 오래 가요. 간장계란밥 필수템 됐어요.", "2026-09-02", "180ml"],
      ["이*진", 4, "부모님께 2병 세트 보냈는데 포장이 꼼꼼했어요. 가격이 조금만 더 착하면 좋겠어요.", "2026-08-15", "300ml × 2병"],
    ],
    mainImage: { src: "/images/products/jobsaba-chamgireum-photo.webp", alt: "크림색 배경 위 잡사바 참기름 병과 종지" },
    extraImages: [{ src: "/images/products/jobsaba-chamgireum-photo-2.webp", alt: "잡사바 참기름 라벨과 참깨 그림 클로즈업" }],
    art: { shape: "oil-bottle", motif: "sesame", fill: "#C7801F", cap: "#B8893A", labelSub: "국산 통참깨 · 저온 압착" },
  }),
  product({
    no: 2,
    slug: "jobsaba-deulgireum",
    name: "잡사바 생들기름",
    summary: "볶지 않은 국산 들깨를 그대로 짜 담은, 구수하고 부드러운 생들기름.",
    categorySlug: "sauce",
    tag: "참기름·들기름",
    storage: "room",
    isBest: true,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 1210,
    createdAt: "2026-06-02T09:00:00+09:00",
    variants: [
      ["JS-SAU-PER-180", "180ml", 15900, 13900, 90],
      ["JS-SAU-PER-300", "300ml", 24900, 21900, 64],
    ],
    foodType: "들기름",
    ingredients: "들깨 100% (국산)",
    origin: "들깨: 국산",
    allergens: "들깨 원료 사용. 참깨를 사용한 제품과 같은 시설에서 착유합니다.",
    shelfLife: "제조일로부터 12개월",
    storageMethod: "개봉 전 서늘한 곳, 개봉 후에는 냉장 보관하고 2개월 안에 드세요.",
    story:
      "들기름은 신선할 때가 제일 맛있습니다. 잡사바 생들기름은 볶지 않은 들깨를 저온에서 바로 짜, 들깨 특유의 풀 향과 고소함을 살렸습니다. 아침에 한 숟갈 그대로 드시는 분도, 묵은지 볶음이나 들기름 막국수에 넉넉히 쓰시는 분도 많습니다.",
    points: [
      { title: "볶지 않은 생들깨", body: "열을 거의 쓰지 않아 들깨 본래의 맑은 향이 납니다." },
      { title: "소량 착유", body: "주문량에 맞춰 짧은 주기로 짜서 출고합니다." },
      { title: "개봉 후 냉장", body: "산패를 늦추려면 개봉 후 냉장고에 두세요." },
    ],
    pairings: ["들기름 막국수", "묵은지 들기름 볶음", "두부 부침 마무리", "김 구이"],
    howTo: "면이나 나물에 넉넉히 두르거나, 두부를 부친 뒤 한 숟갈 끼얹어 보세요. 생으로 드실 때 향이 가장 좋습니다.",
    reviews: [
      ["정*아", 5, "들기름 막국수 해 먹으려고 샀는데 향이 진짜 좋아요. 냉장고에 두고 쓰는 중.", "2026-09-14", "300ml"],
      ["최*민", 4, "생들기름이라 그런지 비린 맛 없이 깔끔합니다. 180ml는 금방 써요.", "2026-08-28", "180ml"],
    ],
    art: { shape: "oil-bottle", motif: "perilla", fill: "#A88F2C", cap: "#3A3530", labelSub: "국산 생들깨 · 저온 착유" },
  }),
  product({
    no: 3,
    slug: "chamggae-ganjang-sauce",
    name: "참깨 마늘 간장소스",
    summary: "볶은 참깨와 익힌 마늘을 갈아 넣은, 따뜻한 채소·두부용 간장소스.",
    categorySlug: "sauce",
    tag: "간장소스",
    storage: "room",
    isBest: false,
    isNew: true,
    isOnePlusOne: false,
    salesCount: 320,
    createdAt: "2026-09-28T09:00:00+09:00",
    variants: [["JS-SAU-GAR-260", "260g", 9800, 8900, 70]],
    foodType: "소스",
    ingredients: "양조간장(대두, 밀) 48%, 참깨 12%, 마늘 10%, 물엿, 다시마 육수, 사과식초",
    origin: "참깨·마늘: 국산 / 대두: 외국산",
    allergens: "대두, 밀, 참깨 함유",
    shelfLife: "제조일로부터 9개월",
    storageMethod: "개봉 전 상온, 개봉 후 냉장 보관",
    story:
      "샐러드 드레싱은 차갑고, 간장은 짭니다. 그 사이를 노린 소스입니다. 참깨를 먼저 볶아 곱게 갈고, 마늘은 익혀서 매운맛은 빼고 단맛만 남겼습니다. 구운 채소와 두부, 샤브샤브 찍먹까지 한 병으로 해결됩니다.",
    points: [
      { title: "볶아서 간 참깨", body: "깨를 통으로 띄우지 않고 갈아 넣어 소스가 진합니다." },
      { title: "익힌 마늘", body: "생마늘의 아린 맛 대신 구수한 단맛을 냅니다." },
      { title: "덜 짠 간장", body: "다시마 육수로 짠맛을 눌러 찍어 먹기 좋습니다." },
    ],
    pairings: ["구운 가지·버섯", "두부 스테이크", "샤브샤브 찍먹", "냉채 드레싱"],
    howTo: "잘 흔들어 쓰세요. 구운 채소에 바로 뿌리거나, 식초 한 숟갈을 더해 냉채 소스로 쓰셔도 좋습니다.",
    reviews: [
      ["윤*서", 5, "두부 구워서 뿌려 먹었는데 고소하고 짜지 않아요. 아이들도 잘 먹어요.", "2026-10-02"],
      ["한*결", 4, "샤브샤브 소스로 딱이에요. 마늘 향이 은근해서 좋네요.", "2026-10-04"],
    ],
    art: { shape: "sauce-bottle", motif: "sesame", fill: "#6B3A1E", cap: "#C9A15B", labelSub: "볶은 참깨 · 익힌 마늘" },
  }),
  product({
    no: 4,
    slug: "manneung-yangnyeom",
    name: "잡사바 만능 양념장",
    summary: "고기 재울 때, 나물 무칠 때, 비빔밥에 두 스푼. 집집마다 한 병씩.",
    categorySlug: "sauce",
    tag: "만능양념",
    storage: "refrigerated",
    isBest: true,
    isNew: false,
    isOnePlusOne: true,
    salesCount: 1520,
    createdAt: "2026-06-10T09:00:00+09:00",
    variants: [
      ["JS-SAU-MAN-320", "320g", 12800, 10900, 80],
      ["JS-SAU-MAN-640", "640g", 22800, 19800, 40],
      ["JS-SAU-MAN-1P1", "320g 1+1 (2병)", 25600, 17900, 30],
    ],
    foodType: "양념소스",
    ingredients: "고추장(쌀, 고춧가루, 대두) 30%, 양조간장(대두, 밀) 22%, 배퓨레 12%, 마늘 8%, 양파, 참기름, 참깨, 생강",
    origin: "고춧가루·마늘·배: 국산 / 대두: 외국산",
    allergens: "대두, 밀, 참깨 함유",
    shelfLife: "제조일로부터 6개월 · 개봉 후 냉장 30일",
    storageMethod: COLD,
    story:
      "고추장과 간장을 반반, 배를 갈아 넣어 단맛은 과일에서 냈습니다. 제육볶음 양념을 따로 만들 필요 없이, 고기 300g에 서너 숟갈이면 끝. 나물 무칠 때는 한 숟갈, 비빔밥엔 두 숟갈. '뭐 넣었어?' 소리 듣는 그 맛입니다.",
    points: [
      { title: "고추장 + 간장 반반", body: "맵기와 짠맛의 균형을 맞춰 어떤 재료에도 어울립니다." },
      { title: "배로 낸 단맛", body: "설탕 대신 국산 배퓨레로 자연스러운 단맛을 냈습니다." },
      { title: "1+1 옵션", body: "많이 쓰는 집을 위해 2병 묶음 옵션을 준비했습니다." },
    ],
    pairings: ["제육볶음·닭갈비", "콩나물·시금치 무침", "비빔밥·비빔국수", "떡볶이 베이스"],
    howTo: "고기 300g 기준 3~4숟갈을 넣고 20분 재운 뒤 볶아 주세요. 나물은 데친 재료 한 줌에 1숟갈이면 충분합니다.",
    reviews: [
      ["오*림", 5, "제육 양념 매번 만들기 귀찮았는데 이걸로 끝. 남편이 식당 맛이래요.", "2026-09-25", "640g"],
      ["강*우", 5, "1+1로 사서 하나는 친정에 드렸어요. 맵기가 적당해서 아이도 먹어요.", "2026-09-10", "320g 1+1 (2병)"],
      ["서*희", 4, "배 맛이 은은하게 나요. 조금 더 매운 버전도 있으면 좋겠어요.", "2026-08-30", "320g"],
    ],
    art: { shape: "glass-jar", motif: "chili", fill: "#9E2A17", cap: "#2F2A26", labelSub: "고기 · 나물 · 비빔밥" },
  }),
  product({
    no: 5,
    slug: "maekom-bibim",
    name: "매콤 비빔장",
    summary: "면도 밥도 한 번에 비벼지는, 새콤달콤 매콤한 붉은 비빔장.",
    categorySlug: "sauce",
    tag: "비빔장",
    storage: "refrigerated",
    isBest: false,
    isNew: false,
    isOnePlusOne: true,
    salesCount: 760,
    createdAt: "2026-06-18T09:00:00+09:00",
    variants: [
      ["JS-SAU-BIB-300", "300g", 8900, 7900, 90],
      ["JS-SAU-BIB-1P1", "300g 1+1 (2병)", 17800, 12900, 40],
    ],
    foodType: "양념소스",
    ingredients: "고추장(쌀, 고춧가루, 대두) 40%, 사과식초, 설탕, 청양고추, 마늘, 참깨, 사과퓨레",
    origin: "고춧가루·청양고추·사과: 국산",
    allergens: "대두, 밀, 참깨 함유",
    shelfLife: "제조일로부터 5개월",
    storageMethod: COLD,
    story:
      "비빔국수 양념은 새콤함과 매운맛이 동시에 와야 맛있습니다. 청양고추는 씨를 덜어 산뜻한 매운맛만, 식초는 사과식초로 날카롭지 않게 맞췄습니다. 국수 한 그릇에 두 숟갈, 밥에는 한 숟갈 반.",
    points: [
      { title: "산뜻한 매운맛", body: "청양고추를 씨를 덜고 갈아 매운맛이 깔끔합니다." },
      { title: "사과식초", body: "새콤함이 부드러워 면에 잘 붙습니다." },
      { title: "만능 비빔", body: "국수, 쫄면, 비빔밥, 회덮밥까지 두루 씁니다." },
    ],
    pairings: ["비빔국수·쫄면", "회덮밥", "골뱅이무침", "오이·양배추 무침"],
    howTo: "삶아 헹군 소면 1인분에 2숟갈, 참기름 한 바퀴를 더하면 완성입니다.",
    reviews: [
      ["임*수", 5, "여름 내내 비빔국수 해 먹었어요. 새콤달콤 비율이 딱 좋아요.", "2026-08-20", "300g 1+1 (2병)"],
      ["조*은", 4, "생각보다 맵지 않고 산뜻해요. 회덮밥에도 잘 어울립니다.", "2026-09-05", "300g"],
    ],
    art: { shape: "glass-jar", motif: "chili", fill: "#B5321C", cap: "#B8893A", labelSub: "국수 · 비빔밥 · 회덮밥" },
  }),
  product({
    no: 6,
    slug: "mat-ganjang-jorim",
    name: "맛간장 조림소스",
    summary: "다시마·표고·사과를 우려낸 맛간장. 조림과 볶음의 간을 한 병으로.",
    categorySlug: "sauce",
    tag: "간장소스",
    storage: "room",
    isBest: false,
    isNew: true,
    isOnePlusOne: false,
    salesCount: 210,
    createdAt: "2026-10-01T09:00:00+09:00",
    variants: [
      ["JS-SAU-MAT-500", "500ml", 9800, 8900, 70],
      ["JS-SAU-MAT-900", "900ml", 15800, 13900, 40],
    ],
    foodType: "소스",
    ingredients: "양조간장(대두, 밀) 60%, 다시마 육수, 표고버섯, 사과, 양파, 물엿, 생강",
    origin: "다시마·표고·사과: 국산 / 대두·밀: 외국산",
    allergens: "대두, 밀 함유",
    shelfLife: "제조일로부터 12개월",
    storageMethod: "개봉 전 서늘한 곳, 개봉 후 냉장 보관",
    story:
      "감자조림, 어묵볶음, 불고기. 간장에 설탕, 맛술, 다시물까지 따로 꺼낼 필요 없이 이 한 병이면 됩니다. 다시마와 표고를 우리고 사과와 양파로 단맛을 냈습니다.",
    points: [
      { title: "육수까지 한 병", body: "다시마·표고 육수를 넣어 따로 국물 낼 필요가 없습니다." },
      { title: "과일로 낸 단맛", body: "사과와 양파로 단맛을 내 뒷맛이 깔끔합니다." },
      { title: "조림·볶음 만능", body: "물 2 : 맛간장 1 비율이면 대부분의 조림이 됩니다." },
    ],
    pairings: ["감자·어묵 조림", "불고기 양념", "계란 장조림", "잡채 간"],
    howTo: "조림은 물 2 : 맛간장 1, 볶음은 재료 200g에 2숟갈을 기준으로 간을 맞춰 보세요.",
    reviews: [
      ["배*나", 5, "감자조림이 한 번에 성공했어요. 단맛이 과하지 않아 좋아요.", "2026-10-05", "500ml"],
      ["신*혁", 4, "불고기 재울 때 썼는데 간이 딱 맞네요. 큰 병으로 재구매 예정.", "2026-10-06", "500ml"],
    ],
    art: { shape: "sauce-bottle", motif: "drop", fill: "#3B1D10", cap: "#2F2A26", labelSub: "조림 · 볶음 · 불고기" },
  }),
  product({
    no: 7,
    slug: "saekom-chojang",
    name: "새콤 초고추장",
    summary: "회와 숙회, 비빔밥까지. 텁텁하지 않고 깔끔한 수제 초고추장.",
    categorySlug: "sauce",
    tag: "양념장",
    storage: "refrigerated",
    isBest: false,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 380,
    createdAt: "2026-07-01T09:00:00+09:00",
    variants: [["JS-SAU-CHO-300", "300g", 6900, 6500, 80]],
    foodType: "양념소스",
    ingredients: "고추장(쌀, 고춧가루, 대두) 45%, 현미식초, 매실청, 설탕, 마늘, 참깨",
    origin: "고춧가루·매실: 국산",
    allergens: "대두, 밀, 참깨 함유",
    shelfLife: "제조일로부터 6개월",
    storageMethod: COLD,
    story: "현미식초와 매실청으로 새콤함을 내 텁텁함 없이 산뜻합니다. 회 한 점, 데친 오징어, 미나리 무침에 곁들여 보세요.",
    points: [
      { title: "현미식초 + 매실청", body: "산미가 둥글고 향이 좋습니다." },
      { title: "묽지도 되지도 않게", body: "찍어도, 비벼도 잘 붙는 농도로 맞췄습니다." },
      { title: "작은 300g", body: "신선할 때 다 쓸 수 있는 크기입니다." },
    ],
    pairings: ["광어·우럭 회", "오징어·문어 숙회", "미나리 초무침", "회덮밥"],
    howTo: "그대로 찍어 드시거나, 무침에는 채소 한 줌에 1숟갈을 넣어 주세요.",
    reviews: [
      ["문*지", 5, "시판 초장보다 덜 달고 깔끔해요. 회 먹는 날 필수.", "2026-09-18"],
      ["장*호", 4, "숙회 찍어 먹기 좋아요. 매실 향이 살짝 나요.", "2026-08-11"],
    ],
    art: { shape: "glass-jar", motif: "chili", fill: "#C2361F", cap: "#C9A15B", labelSub: "회 · 숙회 · 무침" },
  }),
  // ───────────── 장류 ─────────────
  product({
    no: 8,
    slug: "bori-gochujang",
    name: "잡사바 보리고추장",
    summary: "찰보리를 띄워 천천히 삭힌, 구수하고 칼칼한 항아리 고추장.",
    categorySlug: "jang",
    tag: "고추장",
    storage: "room",
    isBest: true,
    isNew: true,
    isOnePlusOne: false,
    salesCount: 1680,
    createdAt: "2026-09-20T09:00:00+09:00",
    variants: [
      ["JS-JNG-BOR-500", "500g", 13900, 11900, 90],
      ["JS-JNG-BOR-1K", "1kg", 24900, 21900, 60],
      ["JS-JNG-BOR-2K", "2kg 항아리", 46900, 39900, 20],
    ],
    foodType: "고추장",
    ingredients: "고춧가루 25%, 찰보리쌀 20%, 메주가루(대두) 10%, 조청, 천일염, 엿기름(보리)",
    origin: "고춧가루·찰보리·대두: 국산",
    allergens: "대두, 밀 함유",
    shelfLife: "제조일로부터 18개월 · 개봉 후 냉장",
    storageMethod: "개봉 전 서늘한 곳, 개봉 후 냉장 보관. 표면이 마르지 않게 눌러 덮어 주세요.",
    story:
      "찹쌀 대신 찰보리로 담갔습니다. 보리는 단맛이 덜하고 구수해서, 고추장 맛이 한결 담백하고 칼칼해집니다. 엿기름으로 삭혀 조청 단맛만 살짝 더했고, 항아리에서 한 철을 넘겨 숙성했습니다. 찌개에 풀면 국물이 맑게 빨갛고, 쌈장에 섞으면 구수함이 배로 납니다.",
    points: [
      { title: "국산 찰보리", body: "보리 특유의 구수함으로 뒷맛이 깔끔합니다." },
      { title: "엿기름 삭힘", body: "설탕을 줄이고 곡물의 단맛으로 맛을 냈습니다." },
      { title: "항아리 숙성", body: "한 철 이상 햇볕과 바람에 익혔습니다." },
    ],
    pairings: ["고추장찌개·제육", "비빔밥", "쌈장 (된장과 1:1)", "떡볶이"],
    howTo: "찌개 2인분에 1.5숟갈, 비빔밥엔 1숟갈. 된장과 1:1로 섞고 참기름·다진 파를 넣으면 바로 쌈장이 됩니다.",
    reviews: [
      ["유*경", 5, "보리 들어간 고추장은 처음인데 구수해서 깜짝 놀랐어요. 찌개가 텁텁하지 않아요.", "2026-10-01", "1kg"],
      ["노*수", 5, "항아리째 받으니 선물 같아요. 맛도 시골 할머니 고추장 느낌.", "2026-09-27", "2kg 항아리"],
      ["황*린", 4, "칼칼하고 덜 달아요. 단맛 좋아하시면 조청 조금 더 넣으세요.", "2026-09-24", "500g"],
    ],
    mainImage: { src: "/images/products/bori-gochujang-photo.webp", alt: "크림색 배경 위 잡사바 보리고추장 항아리 세 개와 종지" },
    extraImages: [{ src: "/images/products/bori-gochujang-photo-2.webp", alt: "잡사바 보리고추장 큰 항아리 라벨 클로즈업" }],
    art: { shape: "onggi", motif: "barley", fill: "#8E2216", cap: "#4A3328", labelSub: "국산 찰보리 · 항아리 숙성" },
  }),
  product({
    no: 9,
    slug: "taeyangcho-gochujang",
    name: "태양초 찹쌀고추장",
    summary: "햇볕에 말린 태양초 고춧가루 비율을 높인, 색 곱고 진한 찹쌀고추장.",
    categorySlug: "jang",
    tag: "고추장",
    storage: "room",
    isBest: true,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 980,
    createdAt: "2026-06-05T09:00:00+09:00",
    variants: [
      ["JS-JNG-TAE-500", "500g", 12900, 11900, 80],
      ["JS-JNG-TAE-1K", "1kg", 22900, 19900, 50],
    ],
    foodType: "고추장",
    ingredients: "태양초 고춧가루 28%, 찹쌀 22%, 메주가루(대두) 10%, 조청, 천일염",
    origin: "고춧가루·찹쌀·대두: 국산",
    allergens: "대두, 밀 함유",
    shelfLife: "제조일로부터 18개월",
    storageMethod: "개봉 전 서늘한 곳, 개봉 후 냉장 보관",
    story: "물엿 단맛을 줄이고 고추 자체의 단맛을 남겼습니다. 볶음과 조림의 시작점으로 한 숟갈이면 색과 맛이 한 번에 잡힙니다.",
    points: [
      { title: "태양초 고춧가루", body: "햇볕에 말린 고추라 색이 곱고 향이 진합니다." },
      { title: "찹쌀로 낸 윤기", body: "찹쌀을 넉넉히 넣어 윤기 있고 부드럽습니다." },
      { title: "덜 단 고추장", body: "물엿 대신 조청을 조금만 썼습니다." },
    ],
    pairings: ["떡볶이", "오징어볶음", "닭볶음탕", "고추장 불고기"],
    howTo: "볶음 요리 2인분에 1~1.5숟갈. 기름에 먼저 볶아 주면 색과 향이 더 살아납니다.",
    reviews: [
      ["송*아", 5, "색이 정말 예뻐요. 떡볶이 하면 빛깔부터 달라요.", "2026-09-12", "1kg"],
      ["권*민", 4, "덜 달아서 좋아요. 매운맛은 중간 정도.", "2026-08-03", "500g"],
    ],
    art: { shape: "onggi", motif: "chili", fill: "#A3281A", cap: "#4A3328", labelSub: "태양초 고춧가루 · 찹쌀" },
  }),
  product({
    no: 10,
    slug: "haetsal-doenjang",
    name: "햇살 재래 된장",
    summary: "메주를 띄워 항아리에 익힌, 소금기 낮고 콩 향 긴 재래 된장.",
    categorySlug: "jang",
    tag: "된장",
    storage: "room",
    isBest: true,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 1120,
    createdAt: "2026-06-01T09:00:00+09:00",
    variants: [
      ["JS-JNG-DOE-500", "500g", 11900, 10900, 70],
      ["JS-JNG-DOE-1K", "1kg", 19900, 17900, 50],
    ],
    foodType: "된장",
    ingredients: "대두 80%, 천일염 18%, 정제수",
    origin: "대두: 국산 / 천일염: 국산",
    allergens: "대두 함유",
    shelfLife: "제조일로부터 24개월",
    storageMethod: "개봉 후 냉장 보관. 표면에 하얀 막(효모)이 생기면 걷어내고 드셔도 됩니다.",
    story: "국산 콩으로 메주를 쑤어 볏짚에 띄우고, 장을 가른 뒤 항아리에서 1년 넘게 익혔습니다. 짠맛은 낮추고 콩의 구수함은 길게 남겨 찌개뿐 아니라 쌈장·무침에도 잘 맞습니다.",
    points: [
      { title: "국산 콩 메주", body: "콩을 직접 삶아 메주를 띄웠습니다." },
      { title: "1년 이상 숙성", body: "항아리에서 천천히 익혀 맛이 깊습니다." },
      { title: "저염 설계", body: "찌개를 끓여도 짜게 졸지 않습니다." },
    ],
    pairings: ["된장찌개", "시래기 된장국", "쌈장", "된장 삼겹살 수육"],
    howTo: "찌개 2인분에 1.5숟갈. 무침에는 된장 1 : 참기름 1 : 다진 마늘 약간으로 섞어 보세요.",
    reviews: [
      ["엄*희", 5, "짜지 않아서 국을 넉넉히 끓여도 좋아요. 콩 향이 진합니다.", "2026-09-08", "1kg"],
      ["차*준", 5, "쌈장으로 먹으려고 샀다가 찌개까지 이걸로 바꿨어요.", "2026-08-22", "500g"],
    ],
    art: { shape: "onggi", motif: "soybean", fill: "#7A4A22", cap: "#4A3328", labelSub: "국산 콩 · 항아리 숙성" },
  }),
  product({
    no: 11,
    slug: "jip-cheonggukjang",
    name: "집 청국장",
    summary: "냄새는 순하게, 콩은 쫀득하게. 한 번 끓일 만큼씩 소분한 냉동 청국장.",
    categorySlug: "jang",
    tag: "청국장",
    storage: "frozen",
    isBest: false,
    isNew: true,
    isOnePlusOne: false,
    salesCount: 260,
    createdAt: "2026-09-30T09:00:00+09:00",
    variants: [
      ["JS-JNG-CHG-200X3", "200g × 3팩", 13500, 11900, 60],
      ["JS-JNG-CHG-200X6", "200g × 6팩", 26000, 21900, 30],
    ],
    foodType: "청국장",
    ingredients: "대두 92% (국산), 천일염, 고춧가루, 마늘",
    origin: "대두·고춧가루·마늘: 국산",
    allergens: "대두 함유",
    shelfLife: "제조일로부터 냉동 6개월",
    storageMethod: "-18℃ 이하 냉동 보관. 해동 후에는 냉장 3일 안에 드시고 재냉동하지 마세요.",
    story: "국산 콩을 짧게 띄워 쿰쿰한 냄새는 줄이고 끈기는 살렸습니다. 두부, 김치, 애호박만 넣고 끓여도 한 끼가 됩니다. 200g 한 팩이 2~3인분 찌개 한 번입니다.",
    points: [
      { title: "순한 냄새", body: "띄우는 시간을 조절해 냄새에 민감한 분도 편하게 드십니다." },
      { title: "1회 소분", body: "200g씩 나눠 얼려 필요한 만큼만 꺼내 씁니다." },
      { title: "냉동 출고", body: "아이스박스와 아이스팩으로 언 상태 그대로 보냅니다." },
    ],
    pairings: ["청국장찌개", "김치 청국장", "청국장 비빔밥", "두부 청국장"],
    howTo: "멸치 육수 500ml에 언 청국장 1팩을 넣고 김치·두부를 더해 10분 끓이면 완성입니다.",
    reviews: [
      ["구*선", 5, "냄새가 생각보다 순해서 아파트에서도 부담 없어요. 소분돼 있어 편합니다.", "2026-10-03", "200g × 3팩"],
      ["안*영", 4, "콩이 살아 있어서 식감이 좋아요. 6팩으로 다시 살게요.", "2026-10-05", "200g × 3팩"],
    ],
    art: { shape: "pouch", motif: "soybean", fill: "#8A6A3A", cap: "#C9A15B", labelSub: "국산 콩 · 1회 소분" },
  }),
  product({
    no: 12,
    slug: "kosomhan-ssamjang",
    name: "고소한 쌈장",
    summary: "재래 된장에 보리고추장, 다진 땅콩을 더한 고소한 쌈장. 고기 먹는 날 필수.",
    categorySlug: "jang",
    tag: "쌈장",
    storage: "room",
    isBest: false,
    isNew: false,
    isOnePlusOne: true,
    salesCount: 640,
    createdAt: "2026-07-05T09:00:00+09:00",
    variants: [
      ["JS-JNG-SSM-450", "450g", 9900, 8500, 80],
      ["JS-JNG-SSM-1P1", "450g 1+1 (2통)", 19800, 14900, 40],
    ],
    foodType: "혼합장",
    ingredients: "된장(대두) 45%, 고추장(고춧가루, 찰보리, 대두) 25%, 땅콩 5%, 참기름, 마늘, 양파, 참깨",
    origin: "대두·고춧가루·마늘: 국산 / 땅콩: 외국산",
    allergens: "대두, 밀, 땅콩, 참깨 함유",
    shelfLife: "제조일로부터 12개월",
    storageMethod: "개봉 후 냉장 보관",
    story: "따로 섞을 필요 없는 쌈장입니다. 재래 된장을 기본으로 보리고추장을 더하고, 볶은 땅콩을 다져 넣어 씹는 맛까지 챙겼습니다.",
    points: [
      { title: "된장 + 보리고추장", body: "잡사바 장 두 가지를 황금비로 섞었습니다." },
      { title: "다진 땅콩", body: "고소함과 씹는 재미를 더했습니다." },
      { title: "1+1 옵션", body: "캠핑·모임 많은 계절에 넉넉하게." },
    ],
    pairings: ["삼겹살·목살 쌈", "오이·고추 찍먹", "쌈밥", "된장 비빔밥"],
    howTo: "그대로 찍어 드시거나, 다진 청양고추를 조금 섞으면 더 칼칼해집니다.",
    reviews: [
      ["홍*진", 5, "캠핑 갈 때마다 챙겨요. 땅콩이 씹혀서 고소해요.", "2026-08-17", "450g 1+1 (2통)"],
      ["백*호", 4, "시판 쌈장보다 덜 달고 된장 맛이 진해요.", "2026-07-29", "450g"],
    ],
    art: { shape: "tray", motif: "soybean", fill: "#7B3B1E", cap: "#D9CDB8", labelSub: "된장 · 보리고추장 · 땅콩" },
  }),
  product({
    no: 13,
    slug: "onggi-joseon-ganjang",
    name: "옹기 조선간장 (국간장)",
    summary: "콩과 소금, 물만으로 맑힌 국간장. 국과 나물 간을 색 없이 맞춥니다.",
    categorySlug: "jang",
    tag: "간장",
    storage: "room",
    isBest: false,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 520,
    createdAt: "2026-06-03T09:00:00+09:00",
    variants: [
      ["JS-JNG-GUK-500", "500ml", 14900, 13900, 60],
      ["JS-JNG-GUK-900", "900ml", 24900, 22900, 30],
    ],
    foodType: "한식간장",
    ingredients: "대두(국산), 천일염(국산), 정제수",
    origin: "대두·천일염: 국산",
    allergens: "대두 함유",
    shelfLife: "제조일로부터 24개월",
    storageMethod: "직사광선을 피해 서늘한 곳에 보관",
    story: "메주로 된장을 가르고 남은 장물을 옹기에서 달여 맑혔습니다. 색은 옅고 맛은 깊어, 미역국·콩나물국·나물무침의 간을 깔끔하게 맞춥니다.",
    points: [
      { title: "콩·소금·물만", body: "첨가물 없이 전통 방식 그대로 담갔습니다." },
      { title: "옅은 색, 깊은 맛", body: "국물 색을 탁하게 만들지 않습니다." },
      { title: "옹기 숙성", body: "숨 쉬는 옹기에서 잡내 없이 익혔습니다." },
    ],
    pairings: ["미역국·소고기무국", "콩나물국", "시금치·고사리 나물", "계란찜 간"],
    howTo: "국 4인분에 1~2숟갈로 시작해 간을 보며 더해 주세요. 진간장보다 짠맛이 강합니다.",
    reviews: [
      ["전*숙", 5, "미역국 끓일 때 이 간장 넣으면 국물이 맑고 맛있어요.", "2026-09-03", "900ml"],
      ["류*아", 4, "짠맛이 강하니 조금씩 넣으세요. 나물 무침에 최고.", "2026-08-09", "500ml"],
    ],
    art: { shape: "sauce-bottle", motif: "soybean", fill: "#4A2A14", cap: "#C9A15B", labelSub: "콩 · 소금 · 물" },
  }),
  product({
    no: 14,
    slug: "jayeon-yangjo-ganjang",
    name: "자연숙성 양조간장",
    summary: "6개월 자연 숙성한 진한 양조간장. 볶음·조림·찍먹 어디든 기본.",
    categorySlug: "jang",
    tag: "간장",
    storage: "room",
    isBest: false,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 450,
    createdAt: "2026-06-03T09:00:00+09:00",
    variants: [
      ["JS-JNG-YAN-500", "500ml", 9900, 8900, 80],
      ["JS-JNG-YAN-900", "900ml", 15900, 14500, 50],
    ],
    foodType: "양조간장",
    ingredients: "탈지대두, 소맥(밀), 천일염, 정제수, 주정",
    origin: "대두·밀: 외국산 / 천일염: 국산",
    allergens: "대두, 밀 함유",
    shelfLife: "제조일로부터 24개월",
    storageMethod: "개봉 후 냉장 보관을 권합니다",
    story: "단기 속성 대신 6개월을 기다렸습니다. 향이 둥글고 감칠맛이 자연스러워, 간장계란밥처럼 간장 맛이 그대로 드러나는 요리에서 차이가 납니다.",
    points: [
      { title: "6개월 자연숙성", body: "온도를 억지로 올리지 않고 천천히 익혔습니다." },
      { title: "둥근 향", body: "날카로운 짠맛보다 감칠맛이 먼저 옵니다." },
      { title: "두루 쓰는 기본 간장", body: "볶음, 조림, 찍먹 모두 잘 맞습니다." },
    ],
    pairings: ["간장계란밥", "불고기·잡채", "전 찍먹 양념장", "버터 간장 볶음"],
    howTo: "찍먹 양념장은 간장 2 : 식초 1 : 물 1에 고춧가루 약간을 더해 보세요.",
    reviews: [
      ["고*현", 5, "간장계란밥 해 먹으니 확실히 향이 달라요.", "2026-09-19", "500ml"],
      ["남*원", 4, "무난하게 다 잘 어울려요. 큰 병이 가성비 좋아요.", "2026-08-25", "900ml"],
    ],
    art: { shape: "sauce-bottle", motif: "drop", fill: "#2E150A", cap: "#2F2A26", labelSub: "6개월 자연숙성" },
  }),
  // ───────────── 젓갈 · 액젓 ─────────────
  product({
    no: 15,
    slug: "myeolchi-aekjeot",
    name: "잡사바 멸치액젓",
    summary: "남해 멸치를 천일염에 2년 삭혀 맑게 내린, 김치와 국물의 감칠맛 기본.",
    categorySlug: "jeotgal",
    tag: "액젓",
    storage: "room",
    isBest: true,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 1350,
    createdAt: "2026-06-08T09:00:00+09:00",
    variants: [
      ["JS-JEO-MYE-500", "500ml", 8900, 7900, 120],
      ["JS-JEO-MYE-1L", "1L", 14900, 12900, 80],
    ],
    foodType: "액젓",
    ingredients: "멸치 75% (국산), 천일염 25% (국산)",
    origin: "멸치: 국산(남해) / 천일염: 국산",
    allergens: "멸치 함유",
    shelfLife: "제조일로부터 24개월",
    storageMethod: "직사광선을 피해 서늘한 곳에 보관. 개봉 후 냉장 보관을 권합니다.",
    story: "봄 멸치를 잡자마자 천일염에 버무려 2년을 기다렸습니다. 위에 뜬 맑은 액만 걸러 담아 비린 맛 없이 깊은 감칠맛이 납니다. 김치 담글 때, 겉절이 무칠 때, 국 간 맞출 때 소금 대신 한 숟갈.",
    points: [
      { title: "남해 봄 멸치", body: "기름이 적당히 오른 봄 멸치만 씁니다." },
      { title: "2년 숙성", body: "충분히 삭혀 비린내 없이 구수합니다." },
      { title: "맑게 거른 액", body: "탁하지 않아 국물 색이 맑습니다." },
    ],
    pairings: ["배추김치·깍두기", "겉절이", "애호박·콩나물국 간", "계란말이"],
    howTo: "국 4인분에 1숟갈을 소금 대신 넣어 보세요. 김치는 배추 1포기 기준 반 컵이 적당합니다.",
    reviews: [
      ["민*경", 5, "김장할 때 이걸로 했는데 비린 맛이 없어요. 시원한 맛이 나요.", "2026-09-29", "1L"],
      ["이*호", 5, "국 끓일 때 소금 대신 쓰는데 맛이 확 살아요.", "2026-09-11", "500ml"],
    ],
    extraImages: [{ src: "/images/products/myeolchi-aekjeot-photo.webp", alt: "잡사바 멸치액젓 병과 종지 사진" }],
    art: { shape: "fish-bottle", motif: "anchovy", fill: "#5A2410", cap: "#1E1C1A", labelSub: "남해 멸치 · 2년 숙성" },
  }),
  product({
    no: 16,
    slug: "kkanari-aekjeot",
    name: "잡사바 까나리액젓",
    summary: "서해 까나리로 담가 깔끔하고 시원한 맛. 겉절이와 무침에 특히 좋아요.",
    categorySlug: "jeotgal",
    tag: "액젓",
    storage: "room",
    isBest: false,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 870,
    createdAt: "2026-06-08T09:00:00+09:00",
    variants: [
      ["JS-JEO-KKA-500", "500ml", 8900, 7900, 100],
      ["JS-JEO-KKA-1L", "1L", 14900, 12900, 70],
    ],
    foodType: "액젓",
    ingredients: "까나리 75% (국산), 천일염 25% (국산)",
    origin: "까나리: 국산(서해) / 천일염: 국산",
    allergens: "해당 원료 외 알레르기 유발물질 없음 (어류 원료 사용)",
    shelfLife: "제조일로부터 24개월",
    storageMethod: "직사광선을 피해 서늘한 곳에 보관. 개봉 후 냉장 보관을 권합니다.",
    story: "까나리액젓은 멸치보다 맛이 가볍고 깔끔합니다. 서해 까나리를 2년 삭혀 맑게 내렸습니다. 겉절이, 파김치, 오이소박이처럼 바로 먹는 김치에 넣으면 시원한 맛이 살아납니다.",
    points: [
      { title: "서해 까나리", body: "봄철 까나리만 골라 담갔습니다." },
      { title: "깔끔한 감칠맛", body: "향이 가벼워 생채·무침에 잘 맞습니다." },
      { title: "2년 숙성", body: "충분히 삭혀 짠맛이 둥급니다." },
    ],
    pairings: ["배추 겉절이", "파김치", "오이소박이", "나물 무침 간"],
    howTo: "겉절이는 배추 반 포기에 3~4숟갈. 나물 무침엔 소금 대신 반 숟갈로 간하세요.",
    reviews: [
      ["윤*정", 5, "겉절이 맛이 깔끔해졌어요. 멸치액젓이랑 섞어 쓰기도 해요.", "2026-09-16", "1L"],
      ["표*수", 4, "향이 강하지 않아서 처음 액젓 쓰는 사람한테도 좋아요.", "2026-08-19", "500ml"],
    ],
    extraImages: [{ src: "/images/products/kkanari-aekjeot-photo.webp", alt: "잡사바 까나리액젓 병과 종지 사진" }],
    art: { shape: "fish-bottle", motif: "sandlance", fill: "#6A2C12", cap: "#9A6A3C", labelSub: "서해 까나리 · 2년 숙성" },
  }),
  product({
    no: 17,
    slug: "chamchi-aek",
    name: "잡사바 참치액",
    summary: "가다랑어 훈연 추출액에 다시마를 더한, 국물 요리 한 숟갈 비법.",
    categorySlug: "jeotgal",
    tag: "액젓",
    storage: "room",
    isBest: true,
    isNew: true,
    isOnePlusOne: false,
    salesCount: 1090,
    createdAt: "2026-09-22T09:00:00+09:00",
    variants: [
      ["JS-JEO-TUN-500", "500ml", 10900, 9500, 100],
      ["JS-JEO-TUN-900", "900ml", 17900, 15500, 60],
    ],
    foodType: "복합조미식품",
    ingredients: "가다랑어 추출액 30% (가다랑어: 원양산), 양조간장(대두, 밀), 다시마 추출액, 정제소금, 설탕, 표고버섯 추출액",
    origin: "가다랑어: 원양산 / 다시마·표고: 국산 / 대두·밀: 외국산",
    allergens: "대두, 밀 함유",
    shelfLife: "제조일로부터 18개월",
    storageMethod: "개봉 전 서늘한 곳, 개봉 후 냉장 보관",
    story: "멸치 다시마 육수를 낼 시간이 없을 때, 한 숟갈이면 국물 맛이 잡힙니다. 훈연한 가다랑어를 우린 진한 추출액에 다시마와 표고를 더해 감칠맛을 겹겹이 쌓았습니다.",
    points: [
      { title: "훈연 가다랑어", body: "은은한 훈연 향이 국물에 깊이를 더합니다." },
      { title: "다시마 · 표고", body: "감칠맛을 세 겹으로 쌓았습니다." },
      { title: "한 숟갈 육수", body: "물 500ml에 1숟갈이면 기본 육수가 됩니다." },
    ],
    pairings: ["어묵탕·우동", "계란말이·계란찜", "떡국·잔치국수", "볶음밥 간"],
    howTo: "물 500ml에 1숟갈로 기본 육수를, 계란말이엔 계란 3개에 반 숟갈을 넣어 보세요.",
    reviews: [
      ["조*린", 5, "어묵탕 끓일 때 한 숟갈 넣으니 가게 맛이 나요.", "2026-10-02", "900ml"],
      ["김*빈", 5, "계란말이에 넣는 게 최고예요. 아이 반찬 필수템.", "2026-09-26", "500ml"],
      ["설*아", 4, "국물이 쉽게 맛있어져요. 조금만 넣어도 됩니다.", "2026-09-23", "500ml"],
    ],
    extraImages: [{ src: "/images/products/chamchi-aek-photo.webp", alt: "잡사바 참치액 병과 종지 사진" }],
    art: { shape: "fish-bottle", motif: "tuna", fill: "#8A4A16", cap: "#C9A15B", labelSub: "훈연 가다랑어 · 다시마" },
  }),
  product({
    no: 18,
    slug: "jeoyeom-myeongnan",
    name: "저염 백명란젓",
    summary: "색소 없이 저염으로 숙성한 통명란. 밥 한 공기가 순식간에 사라집니다.",
    categorySlug: "jeotgal",
    tag: "명란",
    storage: "refrigerated",
    isBest: true,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 1430,
    createdAt: "2026-06-12T09:00:00+09:00",
    variants: [
      ["JS-JEO-MYN-250", "250g", 19900, 16900, 60],
      ["JS-JEO-MYN-500", "500g", 36900, 29900, 40],
    ],
    foodType: "젓갈 (명란젓)",
    ingredients: "명태알 85% (러시아산), 천일염, 마늘, 고춧가루, 참기름, 설탕",
    origin: "명태알: 러시아산 / 고춧가루·마늘: 국산",
    allergens: "명태(알), 참깨 함유",
    shelfLife: "제조일로부터 냉장 30일 / 냉동 6개월",
    storageMethod: COLD_JEOT,
    story: "색소를 넣지 않아 붉지 않은 '백명란'입니다. 소금은 줄이고 저온에서 천천히 숙성해 알이 탱글하고 짜지 않습니다. 그대로 썰어 참기름 한 방울, 김 한 장이면 충분합니다.",
    points: [
      { title: "무색소", body: "인공 색소 없이 명란 본래의 색 그대로입니다." },
      { title: "저염 숙성", body: "짠맛을 낮춰 그대로 드셔도 부담이 적습니다." },
      { title: "통알 선별", body: "터진 알이 적은 통명란만 골랐습니다." },
    ],
    pairings: ["명란 계란말이", "명란 아보카도 덮밥", "명란 크림파스타", "구운 김 + 흰밥"],
    howTo: "먹기 직전 썰어 참기름·깨를 뿌려 드세요. 남은 명란은 한 덩이씩 랩에 싸 냉동하면 오래 둡니다.",
    reviews: [
      ["하*연", 5, "짜지 않아서 그냥 먹어도 맛있어요. 알이 탱글탱글.", "2026-09-30", "500g"],
      ["진*우", 5, "명란 파스타 해 먹었는데 색소 없는 게 마음에 들어요.", "2026-09-13", "250g"],
    ],
    art: { shape: "tray", motif: "roe", fill: "#E59A7E", cap: "#D9CDB8", labelSub: "무색소 · 저염 숙성" },
  }),
  product({
    no: 19,
    slug: "changnan-jeot",
    name: "쫄깃 창난젓",
    summary: "명태 창자를 잘게 썰어 삭힌 오독오독 창난젓. 매콤달콤 밥도둑.",
    categorySlug: "jeotgal",
    tag: "젓갈",
    storage: "refrigerated",
    isBest: false,
    isNew: false,
    isOnePlusOne: true,
    salesCount: 690,
    createdAt: "2026-06-15T09:00:00+09:00",
    variants: [
      ["JS-JEO-CHN-250", "250g", 10900, 9500, 70],
      ["JS-JEO-CHN-1P1", "250g 1+1 (2통)", 21800, 16900, 30],
    ],
    foodType: "젓갈 (양념젓갈)",
    ingredients: "명태창자 66% (러시아산), 고춧가루, 물엿, 천일염, 마늘, 생강, 참깨",
    origin: "명태창자: 러시아산 / 고춧가루: 국산",
    allergens: "명태, 참깨 함유",
    shelfLife: "제조일로부터 냉장 30일 / 냉동 6개월",
    storageMethod: COLD_JEOT,
    story: "창난은 씹는 맛입니다. 잘게 썰어 소금에 삭힌 뒤 고춧가루와 마늘로 양념해, 오독오독한 식감과 매콤달콤한 맛을 살렸습니다.",
    points: [
      { title: "오독한 식감", body: "적당한 두께로 썰어 씹는 맛을 살렸습니다." },
      { title: "매콤달콤 양념", body: "국산 고춧가루로 색과 맛을 냈습니다." },
      { title: "1+1 옵션", body: "냉동해 두고 오래 드실 분께 추천합니다." },
    ],
    pairings: ["흰쌀밥", "무 깍두기와 함께", "참기름 비빔밥", "두부 위에"],
    howTo: "먹을 만큼 덜어 참기름과 다진 파를 조금 넣어 무쳐 드시면 더 맛있습니다.",
    reviews: [
      ["석*희", 5, "식감이 정말 좋아요. 밥 두 공기 순삭.", "2026-09-07", "250g 1+1 (2통)"],
      ["마*준", 4, "생각보다 덜 짜고 달콤해요.", "2026-08-14", "250g"],
    ],
    art: { shape: "tray", motif: "pollock", fill: "#B23A22", cap: "#D9CDB8", labelSub: "오독오독 · 매콤달콤" },
  }),
  product({
    no: 20,
    slug: "ojingeo-jeot",
    name: "몸통 오징어젓",
    summary: "오징어 몸통만 채 썰어 담근, 맵지 않고 쫄깃한 오징어젓.",
    categorySlug: "jeotgal",
    tag: "젓갈",
    storage: "refrigerated",
    isBest: true,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 940,
    createdAt: "2026-06-15T09:00:00+09:00",
    variants: [
      ["JS-JEO-OJI-250", "250g", 9900, 8900, 80],
      ["JS-JEO-OJI-500", "500g", 18900, 15900, 50],
    ],
    foodType: "젓갈 (양념젓갈)",
    ingredients: "오징어 70% (원양산), 고춧가루, 물엿, 천일염, 마늘, 생강, 참깨",
    origin: "오징어: 원양산 / 고춧가루: 국산",
    allergens: "오징어, 참깨 함유",
    shelfLife: "제조일로부터 냉장 30일 / 냉동 6개월",
    storageMethod: COLD_JEOT,
    story: "다리나 귀 없이 몸통만 썼습니다. 그래서 씹을수록 쫄깃하고 모양도 고릅니다. 고춧가루는 색이 돌 정도로만 넣어 아이들도 먹을 수 있게 맵기를 낮췄습니다.",
    points: [
      { title: "몸통만 사용", body: "식감이 고르고 쫄깃합니다." },
      { title: "순한 매운맛", body: "고춧가루를 줄여 누구나 편하게 드십니다." },
      { title: "소포장", body: "250g은 냉장고 한 칸에 쏙 들어갑니다." },
    ],
    pairings: ["흰쌀밥·누룽지", "오이 무침에 섞어서", "주먹밥 속", "김밥 재료"],
    howTo: "오이를 얇게 썰어 오징어젓과 1:1로 무치면 새로운 반찬이 됩니다.",
    reviews: [
      ["권*나", 5, "몸통만이라 그런지 식감이 고급져요.", "2026-09-20", "500g"],
      ["양*석", 4, "아이도 잘 먹을 정도로 순해요. 매운 거 좋아하면 고춧가루 추가!", "2026-08-31", "250g"],
    ],
    art: { shape: "tray", motif: "squid", fill: "#C24A2A", cap: "#D9CDB8", labelSub: "몸통만 · 순한 맛" },
  }),
  product({
    no: 21,
    slug: "eorigul-jeot",
    name: "서해 어리굴젓",
    summary: "작은 서해 굴을 고춧가루에 삭힌, 바다 향 가득한 어리굴젓.",
    categorySlug: "jeotgal",
    tag: "젓갈",
    storage: "refrigerated",
    isBest: false,
    isNew: true,
    isOnePlusOne: false,
    salesCount: 280,
    createdAt: "2026-10-02T09:00:00+09:00",
    variants: [["JS-JEO-EOR-250", "250g", 16900, 14900, 40]],
    foodType: "젓갈 (양념젓갈)",
    ingredients: "굴 65% (국산), 고춧가루, 천일염, 마늘, 생강, 찹쌀풀",
    origin: "굴: 국산(서해) / 고춧가루: 국산",
    allergens: "굴(조개류) 함유",
    shelfLife: "제조일로부터 냉장 20일",
    storageMethod: "0~5℃ 냉장 보관. 굴젓은 냉동하면 식감이 변하니 냉장에서 빨리 드세요.",
    story: "알이 작은 서해 굴을 골라 짧게 삭혔습니다. 굴 향은 살리고 고춧가루로 칼칼하게. 따끈한 밥에 하나 올리면 바다 냄새가 훅 올라옵니다.",
    points: [
      { title: "작은 서해 굴", body: "알이 잘아 양념이 고루 뱁니다." },
      { title: "짧은 숙성", body: "굴 향과 식감을 살리려 오래 두지 않았습니다." },
      { title: "냉장 신선 출고", body: "아이스박스로 차갑게 보냅니다." },
    ],
    pairings: ["갓 지은 흰밥", "보쌈·수육", "두부김치", "굴젓 비빔밥"],
    howTo: "드시기 직전 덜어 내고, 남은 것은 바로 냉장고에 넣어 주세요.",
    reviews: [
      ["오*숙", 5, "굴이 작고 탱탱해요. 보쌈이랑 같이 먹으니 최고.", "2026-10-05"],
      ["김*태", 4, "칼칼하고 맛있는데 빨리 먹어야 해서 소량이 딱 좋아요.", "2026-10-06"],
    ],
    art: { shape: "glass-jar", motif: "oyster", fill: "#B04428", cap: "#2F2A26", labelSub: "서해 굴 · 칼칼한 맛" },
  }),
  product({
    no: 22,
    slug: "saeu-jeot",
    name: "토굴 숙성 새우젓 (추젓)",
    summary: "가을 새우를 토굴에서 숙성한 추젓. 수육과 계란찜, 김장에 꼭.",
    categorySlug: "jeotgal",
    tag: "젓갈",
    storage: "refrigerated",
    isBest: false,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 560,
    createdAt: "2026-06-20T09:00:00+09:00",
    variants: [
      ["JS-JEO-SAE-250", "250g", 9900, 8900, 70],
      ["JS-JEO-SAE-500", "500g", 17900, 15900, 50],
    ],
    foodType: "젓갈 (새우젓)",
    ingredients: "새우 70% (국산), 천일염 30% (국산)",
    origin: "새우·천일염: 국산(서해)",
    allergens: "새우 함유",
    shelfLife: "제조일로부터 냉장 12개월",
    storageMethod: "0~5℃ 냉장 보관 또는 냉동 보관 (염도가 높아 꽁꽁 얼지 않습니다)",
    story: "가을에 잡은 새우로 담근 추젓을 일정한 온도의 토굴에서 숙성했습니다. 새우 모양이 살아 있고 국물이 맑아 수육 찍먹부터 계란찜 간, 김장까지 두루 씁니다.",
    points: [
      { title: "가을 새우 추젓", body: "살이 오른 가을 새우로 담갔습니다." },
      { title: "토굴 숙성", body: "사계절 일정한 온도에서 천천히 익혔습니다." },
      { title: "모양 그대로", body: "새우가 부서지지 않게 담았습니다." },
    ],
    pairings: ["돼지고기 수육", "계란찜·애호박볶음 간", "김장 김치", "콩나물국 간"],
    howTo: "계란찜은 계란 3개에 새우젓 1작은술. 수육엔 다진 파·고춧가루를 살짝 섞어 곁들이세요.",
    reviews: [
      ["정*호", 5, "새우가 통통하고 국물이 맑아요. 수육 먹을 때 꼭 꺼내요.", "2026-09-04", "250g"],
      ["허*진", 4, "김장용으로 500g 샀어요. 짜지만 원래 그런 맛!", "2026-08-27", "500g"],
    ],
    art: { shape: "glass-jar", motif: "shrimp", fill: "#E8C9A8", cap: "#2F2A26", labelSub: "가을 새우 · 토굴 숙성" },
  }),
  product({
    no: 23,
    slug: "galchi-sokjeot",
    name: "남도 갈치속젓",
    summary: "갈치 내장만 삭혀 진하고 구수한 속젓. 쌈 싸 먹을 때 한 점.",
    categorySlug: "jeotgal",
    tag: "젓갈",
    storage: "refrigerated",
    isBest: false,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 340,
    createdAt: "2026-06-20T09:00:00+09:00",
    variants: [["JS-JEO-GAL-250", "250g", 11900, 10900, 50]],
    foodType: "젓갈 (양념젓갈)",
    ingredients: "갈치내장 70% (국산), 천일염, 고춧가루, 마늘, 청양고추",
    origin: "갈치내장: 국산(남해) / 고춧가루: 국산",
    allergens: "해당 원료 외 알레르기 유발물질 없음 (어류 원료 사용)",
    shelfLife: "제조일로부터 냉장 60일 / 냉동 6개월",
    storageMethod: COLD_JEOT,
    story: "남도에서는 쌈을 쌀 때 쌈장 대신 갈치속젓을 올립니다. 갈치 내장만 천일염에 삭혀 진하고 구수합니다. 다진 청양고추와 마늘로 칼칼하게 마무리했습니다.",
    points: [
      { title: "갈치 내장만", body: "진한 감칠맛의 원천입니다." },
      { title: "남도식 양념", body: "청양고추와 마늘로 칼칼하게." },
      { title: "쌈 친구", body: "배추·호박잎 쌈에 쌈장 대신 올려 보세요." },
    ],
    pairings: ["배추·호박잎 쌈", "삼겹살 구이", "찐 양배추", "찌개 감칠맛"],
    howTo: "쌈에 조금씩 올려 드시고, 찌개에는 반 숟갈 풀면 국물이 진해집니다.",
    reviews: [
      ["나*수", 5, "고향 맛이에요. 호박잎 쌈에 올려 먹으니 옛날 생각나요.", "2026-08-30"],
      ["변*아", 4, "처음엔 낯설었는데 삼겹살이랑 먹으니 중독돼요.", "2026-08-12"],
    ],
    art: { shape: "glass-jar", motif: "hairtail", fill: "#7E3A1E", cap: "#B8893A", labelSub: "남해 갈치 · 남도식" },
  }),
  // ───────────── 장아찌 ─────────────
  product({
    no: 24,
    slug: "tongmaneul-jangajji",
    name: "통마늘 간장장아찌",
    summary: "햇마늘을 통째로 간장에 절여, 아린 맛은 빼고 달큰함만 남겼습니다.",
    categorySlug: "jangajji",
    tag: "마늘",
    storage: "refrigerated",
    isBest: true,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 820,
    createdAt: "2026-06-22T09:00:00+09:00",
    variants: [
      ["JS-JJI-GAR-300", "300g", 9900, 8900, 70],
      ["JS-JJI-GAR-600", "600g", 17900, 15900, 40],
    ],
    foodType: "절임식품",
    ingredients: "마늘 60% (국산), 양조간장(대두, 밀), 식초, 설탕, 정제수",
    origin: "마늘: 국산",
    allergens: "대두, 밀 함유",
    shelfLife: "제조일로부터 6개월",
    storageMethod: COLD,
    story: "햇마늘을 식초물에 먼저 담가 아린 맛을 빼고, 간장물을 세 번 끓여 부었습니다. 아삭하면서도 달큰해서 고기 먹을 때 한 알, 입맛 없을 때 한 알.",
    points: [
      { title: "국산 햇마늘", body: "단단한 햇마늘을 통째로 썼습니다." },
      { title: "세 번 끓인 간장물", body: "간이 고루 배고 오래 아삭합니다." },
      { title: "아린 맛 없이", body: "식초물에 먼저 담가 맵지 않습니다." },
    ],
    pairings: ["삼겹살·수육", "라면", "볶음밥 토핑", "장아찌 간장으로 무침"],
    howTo: "남은 장아찌 간장은 버리지 마세요. 나물이나 비빔국수 간장으로 쓰면 좋습니다.",
    reviews: [
      ["곽*연", 5, "아삭하고 하나도 안 매워요. 고기 먹을 때 필수.", "2026-09-15", "600g"],
      ["엄*훈", 4, "단짠 비율 좋아요. 국물도 요리에 씁니다.", "2026-08-21", "300g"],
    ],
    art: { shape: "glass-jar", motif: "garlic", fill: "#B8925A", cap: "#2F2A26", labelSub: "국산 햇마늘 · 간장 절임" },
  }),
  product({
    no: 25,
    slug: "kkaennip-jangajji",
    name: "양념 깻잎장아찌",
    summary: "한 장씩 양념을 바른 깻잎. 밥 한 숟갈 위에 척, 그게 끝입니다.",
    categorySlug: "jangajji",
    tag: "깻잎",
    storage: "refrigerated",
    isBest: true,
    isNew: false,
    isOnePlusOne: true,
    salesCount: 990,
    createdAt: "2026-06-22T09:00:00+09:00",
    variants: [
      ["JS-JJI-KKA-200", "200g", 7900, 6900, 90],
      ["JS-JJI-KKA-1P1", "200g 1+1 (2통)", 15800, 11900, 40],
    ],
    foodType: "절임식품",
    ingredients: "깻잎 55% (국산), 양조간장(대두, 밀), 고춧가루, 양파, 마늘, 참깨, 물엿",
    origin: "깻잎·고춧가루: 국산",
    allergens: "대두, 밀, 참깨 함유",
    shelfLife: "제조일로부터 3개월",
    storageMethod: COLD,
    story: "깻잎을 한 장 한 장 펴서 양념을 발랐습니다. 숨이 죽을 만큼만 절여 향은 살아 있고, 양념은 짜지 않게. 밥 위에 한 장 얹으면 반찬 고민 끝.",
    points: [
      { title: "한 장씩 양념", body: "손으로 바른 양념이 고루 배어 있습니다." },
      { title: "국산 깻잎", body: "향이 진한 국산 깻잎만 씁니다." },
      { title: "1+1 옵션", body: "가족이 많다면 2통 묶음으로." },
    ],
    pairings: ["흰쌀밥", "삼겹살 쌈", "주먹밥", "도시락 반찬"],
    howTo: "젓가락으로 한 장씩 떼어 밥 위에 올려 드세요. 양념이 한쪽에 고이면 통을 뒤집어 두면 됩니다.",
    reviews: [
      ["이*아", 5, "엄마가 해주던 맛이에요. 짜지 않아서 많이 먹게 돼요.", "2026-09-22", "200g 1+1 (2통)"],
      ["도*현", 5, "깻잎 향이 진하고 양념이 넉넉해요.", "2026-09-01", "200g"],
    ],
    art: { shape: "tray", motif: "leaf", fill: "#4E5A26", cap: "#D9CDB8", labelSub: "국산 깻잎 · 한 장씩 양념" },
  }),
  product({
    no: 26,
    slug: "cheongyang-jangajji",
    name: "청양고추 장아찌",
    summary: "씨를 남긴 청양고추를 통으로 절여, 매운 듯 달큰한 맛.",
    categorySlug: "jangajji",
    tag: "고추",
    storage: "refrigerated",
    isBest: false,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 410,
    createdAt: "2026-06-25T09:00:00+09:00",
    variants: [["JS-JJI-CHE-300", "300g", 7900, 7500, 60]],
    foodType: "절임식품",
    ingredients: "청양고추 55% (국산), 양조간장(대두, 밀), 식초, 설탕, 마늘",
    origin: "청양고추: 국산",
    allergens: "대두, 밀 함유",
    shelfLife: "제조일로부터 6개월",
    storageMethod: COLD,
    story: "매운맛은 씨에서 오고, 과육은 의외로 달큰합니다. 잘게 썰어 찌개에 넣거나, 기름진 음식 옆에 그대로 두세요.",
    points: [
      { title: "통 청양고추", body: "구멍을 내 간장물이 속까지 뱁니다." },
      { title: "칼칼한 뒷맛", body: "느끼한 음식 옆에 두면 딱입니다." },
      { title: "다용도", body: "다져서 양념장·찌개에 넣어도 좋습니다." },
    ],
    pairings: ["짜장·라면", "전·튀김", "된장찌개에 송송", "고기 구이"],
    howTo: "송송 썰어 간장 양념장에 섞으면 만두·전 찍먹 소스가 됩니다.",
    reviews: [
      ["추*민", 5, "라면 먹을 때 꼭 꺼내요. 맵지만 계속 손이 가요.", "2026-08-26"],
      ["봉*희", 4, "생각보다 달큰해요. 아주 매운 걸 원하시면 참고하세요.", "2026-08-02"],
    ],
    art: { shape: "glass-jar", motif: "chili", fill: "#4F6B2A", cap: "#B8893A", labelSub: "국산 청양 · 통 절임" },
  }),
  product({
    no: 27,
    slug: "yangpa-jangajji",
    name: "새콤 양파장아찌",
    summary: "햇양파를 큼직하게 썰어 새콤달콤 절인, 고기 짝꿍 장아찌.",
    categorySlug: "jangajji",
    tag: "양파",
    storage: "refrigerated",
    isBest: false,
    isNew: true,
    isOnePlusOne: false,
    salesCount: 230,
    createdAt: "2026-09-26T09:00:00+09:00",
    variants: [
      ["JS-JJI-ONI-400", "400g", 7900, 6900, 70],
      ["JS-JJI-ONI-800", "800g", 13900, 11900, 40],
    ],
    foodType: "절임식품",
    ingredients: "양파 60% (국산), 양조간장(대두, 밀), 사과식초, 설탕, 청양고추, 정제수",
    origin: "양파: 국산",
    allergens: "대두, 밀 함유",
    shelfLife: "제조일로부터 3개월",
    storageMethod: COLD,
    story: "햇양파를 큼직하게 썰어 사과식초로 새콤하게 절였습니다. 고기 기름을 싹 잡아 주는, 아삭한 입가심 장아찌입니다.",
    points: [
      { title: "국산 햇양파", body: "단맛이 좋은 햇양파만 씁니다." },
      { title: "큼직한 썰기", body: "아삭한 식감이 오래 갑니다." },
      { title: "사과식초", body: "새콤함이 부드럽습니다." },
    ],
    pairings: ["삼겹살·족발", "돈가스·튀김", "짜장면", "샌드위치 피클 대신"],
    howTo: "차갑게 두었다 바로 꺼내 드시면 가장 아삭합니다.",
    reviews: [
      ["염*정", 5, "고기 먹을 때 이것만 있으면 돼요. 새콤달콤!", "2026-10-03", "800g"],
      ["피*수", 4, "아삭하고 맛있어요. 국물에 청양 들어가서 살짝 칼칼해요.", "2026-10-04", "400g"],
    ],
    art: { shape: "glass-jar", motif: "onion", fill: "#C9A46A", cap: "#2F2A26", labelSub: "국산 햇양파 · 새콤달콤" },
  }),
  product({
    no: 28,
    slug: "mu-jangajji",
    name: "꼬들 무장아찌",
    summary: "가을 무를 말려 간장에 절인 꼬들꼬들 무장아찌. 참기름에 무쳐 드세요.",
    categorySlug: "jangajji",
    tag: "무",
    storage: "refrigerated",
    isBest: false,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 300,
    createdAt: "2026-06-28T09:00:00+09:00",
    variants: [["JS-JJI-MUU-300", "300g", 6900, 5900, 60]],
    foodType: "절임식품",
    ingredients: "무 65% (국산), 양조간장(대두, 밀), 물엿, 식초, 마늘, 고춧가루",
    origin: "무·고춧가루: 국산",
    allergens: "대두, 밀 함유",
    shelfLife: "제조일로부터 6개월",
    storageMethod: COLD,
    story: "가을 무를 바람에 꾸덕하게 말린 뒤 간장에 절였습니다. 꼬들꼬들한 식감이 살아 있어, 참기름·깨만 넣고 조물조물 무치면 금방 한 접시입니다.",
    points: [
      { title: "가을 무", body: "단단하고 단맛 좋은 가을 무로 담갔습니다." },
      { title: "꾸덕하게 말림", body: "꼬들한 식감이 오래 갑니다." },
      { title: "무쳐 먹는 장아찌", body: "참기름·깨·고춧가루로 쉽게 반찬 완성." },
    ],
    pairings: ["보리밥", "김밥 속", "누룽지·죽", "도시락"],
    howTo: "드실 만큼 덜어 물에 5분 담가 짠기를 빼고, 참기름·깨에 무쳐 보세요.",
    reviews: [
      ["경*아", 5, "꼬들꼬들 식감 최고예요. 죽이랑 먹기 좋아요.", "2026-08-18"],
      ["탁*진", 4, "무쳐 먹으니 할머니 반찬 같아요.", "2026-07-30"],
    ],
    art: { shape: "glass-jar", motif: "radish", fill: "#A86F35", cap: "#B8893A", labelSub: "가을 무 · 꼬들꼬들" },
  }),
  product({
    no: 29,
    slug: "maneuljjong-jangajji",
    name: "마늘쫑 간장장아찌",
    summary: "봄 마늘쫑을 짧게 절여 아삭함이 살아 있는 장아찌.",
    categorySlug: "jangajji",
    tag: "마늘",
    storage: "refrigerated",
    isBest: false,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 360,
    createdAt: "2026-06-28T09:00:00+09:00",
    variants: [["JS-JJI-JJO-300", "300g", 8900, 7900, 60]],
    foodType: "절임식품",
    ingredients: "마늘쫑 60% (국산), 양조간장(대두, 밀), 식초, 설탕, 마른 고추",
    origin: "마늘쫑: 국산",
    allergens: "대두, 밀 함유",
    shelfLife: "제조일로부터 6개월",
    storageMethod: COLD,
    story: "마늘쫑은 데치지 않고 소금에 숨만 죽인 뒤 간장에 넣었습니다. 그래서 오래 두어도 아삭합니다. 밥 위에 몇 가닥이면 한 끼가 됩니다.",
    points: [
      { title: "봄 마늘쫑", body: "연한 봄 마늘쫑만 골랐습니다." },
      { title: "데치지 않음", body: "아삭한 식감을 지키려 생으로 절였습니다." },
      { title: "은은한 마늘 향", body: "맵지 않고 향긋합니다." },
    ],
    pairings: ["흰쌀밥", "고기 구이", "볶음밥 재료", "김밥 속"],
    howTo: "한입 크기로 잘라 그대로 드시거나, 고추장과 참기름에 살짝 무쳐도 좋습니다.",
    reviews: [
      ["문*호", 5, "아삭함이 오래 가요. 밥도둑입니다.", "2026-08-08"],
      ["심*연", 4, "간이 딱 좋아요. 양이 조금 더 많으면 좋겠어요.", "2026-07-25"],
    ],
    art: { shape: "glass-jar", motif: "garlicscape", fill: "#6E7A30", cap: "#2F2A26", labelSub: "봄 마늘쫑 · 아삭" },
  }),

  // ───────────── 반찬 ─────────────
  product({
    no: 30,
    slug: "janmyeolchi-bokkeum",
    name: "바삭 잔멸치볶음",
    summary: "작은 멸치를 한 번 볶아 비린내를 날리고, 바삭하게 마무리했습니다.",
    categorySlug: "banchan",
    tag: "볶음",
    storage: "refrigerated",
    isBest: true,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 1260,
    createdAt: "2026-06-30T09:00:00+09:00",
    variants: [
      ["JS-BAN-MYE-150", "150g", 6900, 5900, 100],
      ["JS-BAN-MYE-300", "300g", 12900, 10900, 60],
    ],
    foodType: "볶음류",
    ingredients: "멸치 55% (국산), 올리고당, 양조간장(대두, 밀), 아몬드, 마늘, 참깨, 식용유",
    origin: "멸치: 국산(남해) / 아몬드: 미국산",
    allergens: "대두, 밀, 참깨, 아몬드 함유",
    shelfLife: "제조일로부터 냉장 14일",
    storageMethod: COLD,
    story: "잔멸치는 마른 팬에 먼저 볶아 비린내와 잔가루를 날리고, 양념은 달라붙을 만큼만 넣었습니다. 도시락 한 칸에 담아도 눅눅해지지 않습니다.",
    points: [
      { title: "남해 지리멸치", body: "작고 부드러운 멸치만 씁니다." },
      { title: "두 번 볶음", body: "마른 볶음 후 양념 볶음으로 바삭합니다." },
      { title: "아몬드 슬라이스", body: "고소함을 더했습니다." },
    ],
    pairings: ["도시락", "주먹밥 속", "김밥", "흰쌀밥"],
    howTo: "냉장고에서 꺼내 바로 드세요. 굳었다면 전자레인지 10초면 다시 부드러워집니다.",
    reviews: [
      ["이*솔", 5, "아이 도시락에 매일 넣어요. 딱딱하지 않고 바삭해요.", "2026-09-28", "300g"],
      ["최*영", 5, "달지 않아서 어른 입맛에도 좋아요.", "2026-09-09", "150g"],
    ],
    art: { shape: "tray", motif: "anchovy", fill: "#C7A06A", cap: "#D9CDB8", labelSub: "남해 지리멸치 · 바삭" },
  }),
  product({
    no: 31,
    slug: "soegogi-jangjorim",
    name: "소고기 메추리알 장조림",
    summary: "결대로 찢은 소고기와 메추리알을 맛간장에 조린, 짜지 않은 장조림.",
    categorySlug: "banchan",
    tag: "조림",
    storage: "refrigerated",
    isBest: true,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 1080,
    createdAt: "2026-06-30T09:00:00+09:00",
    variants: [
      ["JS-BAN-JAN-300", "300g", 12900, 10900, 70],
      ["JS-BAN-JAN-600", "600g", 23900, 19900, 40],
    ],
    foodType: "조림류",
    ingredients: "소고기(홍두깨살) 35% (호주산), 메추리알 25% (국산), 양조간장(대두, 밀), 물엿, 마늘, 꽈리고추, 생강",
    origin: "소고기: 호주산 / 메추리알·꽈리고추: 국산",
    allergens: "쇠고기, 알류(메추리알), 대두, 밀 함유",
    shelfLife: "제조일로부터 냉장 10일",
    storageMethod: COLD,
    story: "홍두깨살을 푹 삶아 결대로 찢고, 메추리알과 꽈리고추를 함께 조렸습니다. 간장은 맛간장으로 짠맛을 눌러, 국물에 밥만 비벼도 맛있습니다.",
    points: [
      { title: "결대로 찢은 고기", body: "부드럽고 국물이 잘 뱁니다." },
      { title: "메추리알 듬뿍", body: "아이들이 제일 먼저 찾는 그 알." },
      { title: "짜지 않은 간", body: "맛간장으로 단짠의 균형을 맞췄습니다." },
    ],
    pairings: ["장조림 버터 비빔밥", "도시락", "계란밥", "죽"],
    howTo: "따뜻한 밥에 장조림과 국물, 버터 한 조각을 올려 비벼 보세요.",
    reviews: [
      ["강*희", 5, "고기가 정말 부드러워요. 메추리알도 넉넉!", "2026-09-17", "600g"],
      ["유*준", 4, "짜지 않아서 아이들이 잘 먹어요.", "2026-08-29", "300g"],
    ],
    art: { shape: "tray", motif: "egg", fill: "#5B2E16", cap: "#D9CDB8", labelSub: "홍두깨살 · 메추리알" },
  }),
  product({
    no: 32,
    slug: "ueong-jorim",
    name: "윤기 우엉조림",
    summary: "채 썬 우엉을 윤기 나게 조린, 씹을수록 달큰한 반찬.",
    categorySlug: "banchan",
    tag: "조림",
    storage: "refrigerated",
    isBest: false,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 520,
    createdAt: "2026-07-02T09:00:00+09:00",
    variants: [["JS-BAN-UEO-200", "200g", 6900, 5900, 60]],
    foodType: "조림류",
    ingredients: "우엉 60% (국산), 양조간장(대두, 밀), 올리고당, 참기름, 참깨",
    origin: "우엉: 국산",
    allergens: "대두, 밀, 참깨 함유",
    shelfLife: "제조일로부터 냉장 14일",
    storageMethod: COLD,
    story: "우엉의 흙내를 식초물에 걷어 내고, 간장과 올리고당으로 윤기 나게 조렸습니다. 김밥 속으로도, 밥반찬으로도 그만입니다.",
    points: [
      { title: "국산 우엉", body: "향이 진한 국산 우엉만 씁니다." },
      { title: "식초물 손질", body: "아린 맛과 흙내를 뺐습니다." },
      { title: "윤기 조림", body: "식어도 딱딱해지지 않습니다." },
    ],
    pairings: ["김밥", "도시락", "흰쌀밥", "유부초밥 속"],
    howTo: "그대로 드시거나, 잘게 다져 유부초밥 밥에 섞어 보세요.",
    reviews: [
      ["임*아", 5, "김밥 쌀 때 이거 하나면 편해요. 맛도 좋아요.", "2026-08-24"],
      ["황*수", 4, "달큰하고 쫄깃해요. 양이 조금 적은 느낌.", "2026-08-06"],
    ],
    art: { shape: "tray", motif: "burdock", fill: "#5A3418", cap: "#D9CDB8", labelSub: "국산 우엉 · 윤기 조림" },
  }),
  product({
    no: 33,
    slug: "kongjaban",
    name: "검은콩 콩자반",
    summary: "껍질이 터지지 않게 여러 번 나눠 조린, 쫀득한 검은콩자반.",
    categorySlug: "banchan",
    tag: "조림",
    storage: "refrigerated",
    isBest: false,
    isNew: false,
    isOnePlusOne: true,
    salesCount: 610,
    createdAt: "2026-07-02T09:00:00+09:00",
    variants: [
      ["JS-BAN-KON-200", "200g", 6500, 5900, 80],
      ["JS-BAN-KON-1P1", "200g 1+1 (2팩)", 13000, 9900, 40],
    ],
    foodType: "조림류",
    ingredients: "검은콩(서리태) 60% (국산), 양조간장(대두, 밀), 설탕, 올리고당, 참깨",
    origin: "검은콩: 국산",
    allergens: "대두, 밀, 참깨 함유",
    shelfLife: "제조일로부터 냉장 21일",
    storageMethod: COLD,
    story: "국산 서리태를 하룻밤 불린 뒤 간장과 설탕을 여러 번 나눠 들였습니다. 껍질이 터지지 않아 반짝이고, 쫀득하지만 딱딱하지 않습니다.",
    points: [
      { title: "국산 서리태", body: "알이 굵고 고소한 서리태로 조렸습니다." },
      { title: "나눠 조리기", body: "간이 속까지 고루 뱁니다." },
      { title: "쫀득한 식감", body: "딱딱하지 않고 촉촉합니다." },
    ],
    pairings: ["흰쌀밥", "도시락", "콩자반 주먹밥", "죽"],
    howTo: "냉장고에서 꺼내 바로 드세요. 밥에 섞어 주먹밥을 만들어도 좋습니다.",
    reviews: [
      ["방*연", 5, "딱딱하지 않아서 어르신들도 잘 드세요.", "2026-09-06", "200g 1+1 (2팩)"],
      ["채*민", 4, "적당히 달고 윤기가 좌르르.", "2026-08-16", "200g"],
    ],
    art: { shape: "tray", motif: "soybean", fill: "#1F1A17", cap: "#D9CDB8", labelSub: "국산 서리태 · 쫀득" },
  }),
  product({
    no: 34,
    slug: "mumallaengi-muchim",
    name: "오독 무말랭이무침",
    summary: "볕에 말린 무를 고춧가루 양념에 버무린 오독오독 무말랭이.",
    categorySlug: "banchan",
    tag: "무침",
    storage: "refrigerated",
    isBest: false,
    isNew: true,
    isOnePlusOne: false,
    salesCount: 240,
    createdAt: "2026-09-29T09:00:00+09:00",
    variants: [["JS-BAN-MUM-250", "250g", 6900, 5900, 70]],
    foodType: "무침류",
    ingredients: "무말랭이 45% (국산), 고춧잎, 고춧가루, 물엿, 멸치액젓, 마늘, 참깨",
    origin: "무·고춧잎·고춧가루: 국산",
    allergens: "멸치, 참깨 함유",
    shelfLife: "제조일로부터 냉장 21일",
    storageMethod: COLD,
    story: "가을 무를 볕에 바싹 말린 뒤 물에 살짝 불려 양념했습니다. 고춧잎을 넣어 향을 더하고, 잡사바 멸치액젓으로 감칠맛을 냈습니다.",
    points: [
      { title: "볕에 말린 무", body: "단맛이 농축돼 씹을수록 달큰합니다." },
      { title: "고춧잎 듬뿍", body: "향긋함과 식감을 더했습니다." },
      { title: "잡사바 액젓 양념", body: "멸치액젓으로 깊은 맛을 냈습니다." },
    ],
    pairings: ["보쌈", "흰쌀밥", "칼국수", "김밥 곁들임"],
    howTo: "꺼내 바로 드시면 됩니다. 참기름 한 방울을 더하면 고소함이 살아납니다.",
    reviews: [
      ["노*아", 5, "오독오독 식감이 너무 좋아요. 보쌈이랑 찰떡.", "2026-10-02"],
      ["서*진", 4, "맵기 적당하고 고춧잎 향이 좋아요.", "2026-10-04"],
    ],
    art: { shape: "tray", motif: "radish", fill: "#B5401F", cap: "#D9CDB8", labelSub: "볕에 말린 무 · 고춧잎" },
  }),
  product({
    no: 35,
    slug: "jinmichae-bokkeum",
    name: "부드러운 진미채볶음",
    summary: "마요네즈로 한 번 버무려 딱딱하지 않은, 달콤 매콤 진미채.",
    categorySlug: "banchan",
    tag: "볶음",
    storage: "refrigerated",
    isBest: false,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 700,
    createdAt: "2026-07-05T09:00:00+09:00",
    variants: [
      ["JS-BAN-JIN-150", "150g", 7900, 6900, 80],
      ["JS-BAN-JIN-300", "300g", 14900, 12900, 40],
    ],
    foodType: "볶음류",
    ingredients: "조미오징어채 55% (오징어: 원양산), 고추장(쌀, 대두), 올리고당, 마요네즈(대두유, 난황), 마늘, 참깨",
    origin: "오징어: 원양산 / 고춧가루: 국산",
    allergens: "오징어, 대두, 밀, 알류(난황), 참깨 함유",
    shelfLife: "제조일로부터 냉장 21일",
    storageMethod: COLD,
    story: "진미채를 살짝 불린 뒤 마요네즈에 먼저 버무려, 냉장고에서 꺼내도 딱딱하지 않습니다. 고추장 양념은 달콤 매콤하게.",
    points: [
      { title: "말랑한 식감", body: "마요네즈 코팅으로 굳지 않습니다." },
      { title: "달콤 매콤", body: "아이와 어른 모두 좋아하는 맛." },
      { title: "도시락 단골", body: "식어도 맛있습니다." },
    ],
    pairings: ["도시락", "흰쌀밥", "김밥", "맥주 안주"],
    howTo: "그대로 드세요. 참깨를 더 뿌리면 더 고소합니다.",
    reviews: [
      ["주*희", 5, "진짜 안 딱딱해요. 남편 도시락 반찬 1순위.", "2026-09-19", "300g"],
      ["오*석", 4, "달콤해서 아이가 잘 먹어요.", "2026-08-23", "150g"],
    ],
    art: { shape: "tray", motif: "squid", fill: "#C0502C", cap: "#D9CDB8", labelSub: "말랑 진미채 · 달콤 매콤" },
  }),
  // ───────────── 세트·선물 ─────────────
  product({
    no: 36,
    slug: "jangdok-samjong-set",
    name: "장독 삼종 선물세트",
    summary: "보리고추장·재래 된장·조선간장을 한 상자에. 찬장의 기본을 선물하세요.",
    categorySlug: "gift",
    tag: "장류 세트",
    storage: "room",
    isBest: true,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 640,
    createdAt: "2026-07-10T09:00:00+09:00",
    variants: [["JS-GFT-JAN-3", "고추장 500g + 된장 500g + 간장 500ml", 40700, 34900, 40]],
    foodType: "고추장, 된장, 한식간장 (세트)",
    ingredients: "구성 상품별 원재료는 각 상품 라벨 참조 (보리고추장 · 햇살 재래 된장 · 옹기 조선간장)",
    origin: "구성 상품과 동일 (대두·고춧가루·찰보리: 국산)",
    allergens: "대두, 밀 함유",
    shelfLife: "구성품 중 가장 짧은 소비기한을 따릅니다 (제조일로부터 18개월 이상)",
    storageMethod: "개봉 전 서늘한 곳, 개봉 후 각 제품 냉장 보관",
    story: "명절, 이사, 결혼 선물로 가장 많이 찾는 구성입니다. 잡사바 장 세 가지를 크림색 선물 상자에 담고, 메시지 카드를 함께 넣어 드립니다. 받는 분 찬장에서 오래 쓰이는 선물입니다.",
    points: [
      { title: "대표 장 세 가지", body: "보리고추장 · 재래 된장 · 조선간장." },
      { title: "선물 상자 + 카드", body: "주문 메모에 문구를 남기면 카드에 적어 넣어 드립니다." },
      { title: "쇼핑백 동봉", body: "직접 전달하실 수 있게 쇼핑백을 함께 보냅니다." },
    ],
    pairings: ["명절 선물", "집들이·이사 선물", "부모님 선물", "감사 인사"],
    howTo: "받으신 뒤 개봉 전에는 서늘한 곳에, 개봉 후에는 냉장 보관해 주세요.",
    reviews: [
      ["윤*희", 5, "시댁에 보냈는데 포장이 고급스럽다고 칭찬 들었어요.", "2026-09-18"],
      ["장*수", 5, "카드 문구도 정성껏 써 주셨어요. 추석 선물로 최고.", "2026-09-10"],
    ],
    art: { shape: "gift-box", motif: "barley", fill: "#8E2216", cap: "#D1271E", labelSub: "고추장 · 된장 · 간장" },
  }),
  product({
    no: 37,
    slug: "chamdeul-gireum-set",
    name: "참·들기름 선물세트",
    summary: "통참깨 참기름과 생들기름 두 병에 볶음참깨까지 담은 선물 상자.",
    categorySlug: "gift",
    tag: "기름 세트",
    storage: "room",
    isBest: true,
    isNew: true,
    isOnePlusOne: false,
    salesCount: 720,
    createdAt: "2026-09-18T09:00:00+09:00",
    variants: [
      ["JS-GFT-OIL-2", "참기름 300ml + 들기름 300ml + 볶음참깨 100g", 58800, 46900, 50],
      ["JS-GFT-OIL-2S", "참기름 180ml + 들기름 180ml", 32800, 26900, 50],
    ],
    foodType: "참기름, 들기름, 볶음참깨 (세트)",
    ingredients: "참기름: 참깨 100% / 들기름: 들깨 100% / 볶음참깨: 참깨 100%",
    origin: "참깨·들깨: 국산",
    allergens: "참깨, 들깨 함유",
    shelfLife: "참기름 18개월, 들기름 12개월, 볶음참깨 12개월 (제조일로부터)",
    storageMethod: "참기름·참깨는 서늘한 곳, 들기름은 개봉 후 냉장 보관",
    story: "고소함을 선물하는 가장 쉬운 방법. 잡사바 통참깨 참기름과 생들기름을 한 상자에 담았습니다. 큰 구성에는 볶음참깨 한 봉을 더했습니다.",
    points: [
      { title: "국산 깨 100%", body: "참깨, 들깨 모두 국산만 씁니다." },
      { title: "두 가지 크기", body: "300ml 큰 구성과 180ml 실속 구성." },
      { title: "안전 포장", body: "병마다 완충재를 넣어 파손을 막습니다." },
    ],
    pairings: ["명절 선물", "부모님 선물", "신혼 선물", "거래처 선물"],
    howTo: "들기름은 개봉 후 냉장 보관하도록 받는 분께 한마디 전해 주세요.",
    reviews: [
      ["송*희", 5, "부모님이 참기름 향 좋다고 또 보내 달래요.", "2026-09-25", "참기름 300ml + 들기름 300ml + 볶음참깨 100g"],
      ["강*호", 4, "실속 구성으로 회사 동료들 선물했어요. 반응 좋아요.", "2026-09-21", "참기름 180ml + 들기름 180ml"],
    ],
    art: { shape: "gift-box", motif: "sesame", fill: "#C7801F", cap: "#D1271E", labelSub: "참기름 · 들기름" },
  }),
  product({
    no: 38,
    slug: "aekjeot-samjong-set",
    name: "액젓 3종 세트",
    summary: "멸치·까나리·참치, 쓰임이 다른 액젓 세 병을 한 번에.",
    categorySlug: "gift",
    tag: "액젓 세트",
    storage: "room",
    isBest: false,
    isNew: true,
    isOnePlusOne: false,
    salesCount: 410,
    createdAt: "2026-09-24T09:00:00+09:00",
    variants: [["JS-GFT-AEK-3", "멸치·까나리·참치 각 500ml", 28700, 23900, 50]],
    foodType: "액젓, 복합조미식품 (세트)",
    ingredients: "멸치액젓: 멸치, 천일염 / 까나리액젓: 까나리, 천일염 / 참치액: 가다랑어 추출액, 양조간장(대두, 밀) 외",
    origin: "멸치·까나리·천일염: 국산 / 가다랑어: 원양산",
    allergens: "멸치, 대두, 밀 함유",
    shelfLife: "구성품 중 가장 짧은 소비기한을 따릅니다 (제조일로부터 18개월)",
    storageMethod: "직사광선을 피해 서늘한 곳에 보관, 개봉 후 냉장 보관",
    story: "김치엔 멸치, 겉절이엔 까나리, 국물엔 참치. 쓰임이 다른 액젓 세 가지를 나란히 두고 골라 쓰세요. 김장철 선물로도 반응이 좋습니다.",
    points: [
      { title: "세 가지 쓰임", body: "김치·무침·국물에 맞춰 골라 씁니다." },
      { title: "500ml × 3병", body: "처음 써 보기 좋은 크기입니다." },
      { title: "단품보다 알뜰", body: "단품 세 병 합계보다 저렴합니다." },
    ],
    pairings: ["김장 준비", "자취 시작 선물", "집밥 입문 세트", "명절 음식"],
    howTo: "멸치는 김치·국, 까나리는 겉절이·나물, 참치액은 국물·계란 요리에 써 보세요.",
    reviews: [
      ["하*정", 5, "세 가지 비교하면서 쓰는 재미가 있어요. 참치액 최고.", "2026-10-01"],
      ["문*빈", 4, "자취하는 동생한테 보냈어요. 요리가 쉬워졌대요.", "2026-09-27"],
    ],
    mainImage: { src: "/images/products/aekjeot-samjong-set-photo.webp", alt: "크림색 배경 위 잡사바 멸치·까나리·참치 액젓 세 병과 종지" },
    art: { shape: "gift-box", motif: "anchovy", fill: "#5A2410", cap: "#D1271E", labelSub: "멸치 · 까나리 · 참치" },
  }),
  product({
    no: 39,
    slug: "jeotgal-modum-set",
    name: "밥도둑 젓갈 모둠",
    summary: "백명란·창난젓·오징어젓을 150g씩. 젓갈 좋아하는 분께 딱.",
    categorySlug: "gift",
    tag: "젓갈 세트",
    storage: "refrigerated",
    isBest: false,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 380,
    createdAt: "2026-07-15T09:00:00+09:00",
    variants: [["JS-GFT-JEO-3", "명란·창난·오징어 각 150g", 31900, 26900, 40]],
    foodType: "젓갈 (세트)",
    ingredients: "구성 상품별 원재료는 각 상품 라벨 참조 (저염 백명란젓 · 쫄깃 창난젓 · 몸통 오징어젓)",
    origin: "명태알·명태창자: 러시아산 / 오징어: 원양산 / 고춧가루: 국산",
    allergens: "명태, 오징어, 참깨 함유",
    shelfLife: "제조일로부터 냉장 30일 / 냉동 6개월",
    storageMethod: COLD_JEOT,
    story: "젓갈 세 가지를 조금씩 맛볼 수 있게 150g씩 담았습니다. 보냉 상자와 아이스팩으로 차갑게 보내 드립니다.",
    points: [
      { title: "인기 젓갈 3종", body: "백명란, 창난, 오징어젓." },
      { title: "150g씩 소분", body: "남기지 않고 신선할 때 드시기 좋습니다." },
      { title: "보냉 포장", body: "아이스박스 + 아이스팩으로 출고합니다." },
    ],
    pairings: ["명절 상차림", "부모님 선물", "캠핑 밥상", "흰쌀밥"],
    howTo: "받으시면 바로 냉장, 오래 두실 젓갈은 냉동해 주세요.",
    reviews: [
      ["엄*자", 5, "세 가지 다 맛있어요. 명란이 특히 짜지 않아요.", "2026-09-14"],
      ["김*현", 4, "보냉 포장이 꼼꼼해서 여름에도 안심이었어요.", "2026-08-20"],
    ],
    art: { shape: "gift-box", motif: "roe", fill: "#B23A22", cap: "#D1271E", labelSub: "명란 · 창난 · 오징어" },
  }),
  product({
    no: 40,
    slug: "bapdoduk-banchan-set",
    name: "밥도둑 반찬 4종 세트",
    summary: "멸치볶음·장조림·콩자반·깻잎장아찌. 일주일 반찬 걱정 끝.",
    categorySlug: "gift",
    tag: "반찬 세트",
    storage: "refrigerated",
    isBest: true,
    isNew: false,
    isOnePlusOne: false,
    salesCount: 860,
    createdAt: "2026-07-15T09:00:00+09:00",
    variants: [["JS-GFT-BAN-4", "4종 (각 150~200g)", 33500, 27900, 50]],
    foodType: "볶음류, 조림류, 절임식품 (세트)",
    ingredients: "구성 상품별 원재료는 각 상품 라벨 참조 (바삭 잔멸치볶음 · 소고기 메추리알 장조림 · 검은콩 콩자반 · 양념 깻잎장아찌)",
    origin: "멸치·메추리알·검은콩·깻잎: 국산 / 소고기: 호주산",
    allergens: "대두, 밀, 참깨, 아몬드, 쇠고기, 알류 함유",
    shelfLife: "구성품 중 가장 짧은 소비기한을 따릅니다 (제조일로부터 냉장 10일)",
    storageMethod: COLD,
    story: "가장 많이 팔리는 반찬 네 가지를 한 번에. 혼자 사는 자녀에게, 바쁜 맞벌이 집에, 출산한 친구에게. 냉장고에 넣어 두면 일주일 밥상이 든든합니다.",
    points: [
      { title: "베스트 반찬 4종", body: "멸치볶음 · 장조림 · 콩자반 · 깻잎장아찌." },
      { title: "냉장 신선 출고", body: "아이스팩과 함께 보냉 상자로 보냅니다." },
      { title: "선물 메시지", body: "주문 메모에 남기면 카드에 적어 드립니다." },
    ],
    pairings: ["자취생 응원", "출산·산후 선물", "맞벌이 집밥", "부모님 반찬"],
    howTo: "받는 즉시 냉장 보관하고, 장조림은 먼저 드세요.",
    reviews: [
      ["정*연", 5, "자취하는 아들한테 보냈는데 일주일 잘 먹었대요.", "2026-09-23"],
      ["손*희", 5, "출산한 친구 선물로 보냈어요. 너무 고마워하더라고요.", "2026-09-05"],
    ],
    art: { shape: "gift-box", motif: "egg", fill: "#5B2E16", cap: "#D1271E", labelSub: "반찬 4종" },
  }),
];

export function catalogProductBySlug(slug: string) {
  return CATALOG_PRODUCTS.find((item) => item.slug === slug) ?? null;
}

export function catalogCategoryBySlug(slug: string) {
  return CATALOG_CATEGORIES.find((item) => item.slug === slug) ?? null;
}
